default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: monster_mapper_development
  username: postgres
  password: admin

test:
  <<: *default
  database: monster_mapper_test

production:
  <<: *default
  database: monster_mapper_production
  username: monster_mapper
  password: <%= ENV['MONSTER_MAPPER_DATABASE_PASSWORD'] %>
